name = "AbstractGPsMakie"
uuid = "7834405d-1089-4985-bd30-732a30b92057"
authors = ["David Widmann"]
version = "0.2.7"

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
AbstractGPs = "0.3, 0.4, 0.5"
Makie = "0.15.2, 0.16, 0.17, 0.18, 0.19, 0.20"
julia = "1.3"
