[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
AbstractGPsMakie = "7834405d-1089-4985-bd30-732a30b92057"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
AbstractGPs = "0.3, 0.4, 0.5"
AbstractGPsMakie = "0.2"
CairoMakie = "0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.15"
Documenter = "1"
julia = "1.3"
